name: 🧪 Unit Testing
on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install Dependencies & Run Test
        run: |
          npm ci
          npm run test
